add

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -14,14 +14,15 @@ pipeline {
         stage ('Validate Jira') {
           steps {
             script {
-
-
-
+              def comment
+              def issue
                // validate that ddtl number is found within Git Commit message
                if (ddtl_ID == "") {
                  echo "NO Commit msg found within Git Commit message Error 120"
                  echo "##########################"
-                 def comment = "${BUILD_URL} FAILED - ${ERROR}"
+
+                 comment = "${BUILD_URL} FAILED - ${ERROR}"
+
                  currentBuild.result = 'FAILURE'
                  exit 120
 
@@ -30,56 +31,57 @@ pipeline {
                  echo ddtl_ID
                }
 
-               script {
                  // retrieving jira issue
-                 try {
-                   def issue = jiraGetIssue idOrKey: ddtl_ID, site: jiraSite
-                   echo issue.data.toString()
+              try {
+                   issue = jiraGetIssue idOrKey: ddtl_ID, site: jiraSite
 
-                 } catch (ERROR) {
+
+                   if ( issue.data.toString() == "" ) {
+                         echo "The following Jira Issues are not found in" jiraSite ddtl_ID
+                         echo "ERROR  message Error 130"
+                         echo "##########################"
+                         def comment = "${BUILD_URL} FAILED - ${ERROR}"
+                         currentBuild.result = 'FAILURE'
+                         exit 130
+                   } else {
+                     echo issue.data.toString()
+                   }
+
+              } catch (ERROR) {
                    echo "The following Jira Issues are not found in" jiraSite ddtl_ID
                    echo "ERROR  message Error 130"
                    echo "##########################"
                    def comment = "${BUILD_URL} FAILED - ${ERROR}"
                    currentBuild.result = 'FAILURE'
                    exit 130
-                 }
-
-                 // exit if
-                 if ( issue.data.toString() == "" ) {
-                   echo "The following Jira Issues are not found in" jiraSite ddtl_ID
-                   echo "ERROR  message Error 130"
-                   echo "##########################"
-                   def comment = "${BUILD_URL} FAILED - ${ERROR}"
-                   currentBuild.result = 'FAILURE'
-                   exit 130
-                 }
-
-
-
-                 try {
-
-                     jiraAddComment idOrKey: $ddtlIDs, comment: comment, site: $jiraSite
-
-
-                     def transitionInput = [ transition: [ name: $buildSuccessTransition ] ]
-                     jiraTransitionIssue idOrKey: $ddtlIDs, input: transitionInput, site: $jiraSite
-
-                } catch (error) {
-                     def comment = "${BUILD_URL} FAILED - ${ERROR}"
-                     jiraAddComment idOrKey: $ddtlIDs, comment: comment, site: $jiraSite
-                     currentBuild.result = 'FAILURE'
-               }
-           }
-
-            }
+              }  // End of Try block
+            }  // End of script block
         }} // End of Validate Jira stage and Step
 
 
 
         stage('Build') {
             steps {
-                sh 'mvn -B -DskipTests clean package'
+                sh 'mvn -v'
+                echo "Build package"
+
+                // if Build success then
+                script {
+
+                  try {
+                          jiraAddComment idOrKey: ddtl_ID, comment: comment, site: jiraSite
+                          def transitionInput = [ transition: [ name: buildSuccessTransition ] ]
+                          jiraTransitionIssue idOrKey: ddtl_ID, input: transitionInput, site: jiraSite
+
+                     } catch (error) {
+                          def comment = "${BUILD_URL} FAILED - ${ERROR}"
+                          jiraAddComment idOrKey: ddtl_ID, comment: comment, site: jiraSite
+                          currentBuild.result = 'FAILURE'
+                    }
+
+                }
+
+
         }} //End of Build Stage
 
         stage('Test') {
